class AlreadyFollowingException(Exception):
    pass


class NotFollowingException(Exception):
    pass
